### ISSUE TITLE
todoitems.json is not loaded via Component-preload.js

### ISSUE THREAD

**Issue by KeKsBoTer** [SAP/openui5-sample-app#109]
I just cloned the repo and built it using `npm run build` and then `npm run serve-dist` to serve the app.
I realized that the file `webapp/model/todoitems.json` is in Component-repload.json but is loaded separately via a HTTP GET request.

Is this intended? 
Is there a way to avoid the additional request and use the Component-preload?
Otherwise I think the `todoitems.json` should be removed from the Component-preload.

Tested with following versions:

- @ui5/cli  2.10.0
- OpenUI5 1.87.0

**Comment by RandomByte** [comment]
Hi Simon, good observation!

The additional request is indeed intended. The JSON Model takes care of loading data by itself. In typical scenarios the model data might change or come from a different host. There's not really a use case for having it statically as part of the project resources while still asking the JSON Model to load it, since you could just pass the json to the model directly.

And of course you are right: In this case the JSON should not be part of the Component-preload.js bundle. This is actually an issue of the UI5 Tooling which we also spotted in a different context a while ago. A fix is already in the making: https://github.com/SAP/ui5-builder/pull/580

**Comment by RandomByte** [comment]
The fix has just been released as part of UI5 CLI [v2.10.1](https://github.com/SAP/ui5-cli/releases/tag/v2.10.1) and can be tested on the current master of the openui5-sample-app 👍
