### ISSUE TITLE
Use source maps or something when debugging the UI5?

### ISSUE THREAD

**Issue by smilingsun** [SAP/openui5-sample-app#21]
I really love the this project and it gave me more freedom and imagination using Grunt and Karma, thanks so much!

But I was wondering, how can I use the ***un-uglified version*** of UI5  from bower when I'm debugger the UI5? Maybe using source maps, or ``xxx-dbg.js`` when I load the UI5 from CDN)

The current debugging is a little bit hard to read the variable names in UI5 source code, as below:
![screen shot 2017-08-30 at 1 58 52 am](https://user-images.githubusercontent.com/4011348/29836486-f8a771f0-8d27-11e7-8489-2223873ab42b.png)

**Comment by tobiasso85** [comment]
Hi @smilingsun,

thanks for your feedback.

You could use the debugging mode in order to debug the un-uglified sources. The sources would then be loaded one by one instead of the minified bundled version.

[Debugging](https://sapui5.hana.ondemand.com/sdk/#docs/guide/c9b0f8cca852443f9b8d3bf8ba5626ab.html)


Regards
