### ISSUE TITLE
Cannot access the application when hooking the source code into a container of docker

### ISSUE THREAD

**Issue by lenient** [SAP/openui5-sample-app#57]
I'm using the command below to link my local source code into a container of docker,
`docker run -p 8080:8080 -v $(pwd):/var/www -w "/var/www" node npm start`

And it returns the following logs in the console,
```
> openui5-sample-app@0.2.0 start /var/www
> ui5 serve

WARN types:library:LibraryFormatter Failed to detect namespace or namespace is empty for project themelib_sap_fiori_3. Check verbose log for details.
Server started
URL: http://localhost:8080
```

But I cannot access the http://localhost:8080, it shows failed.

Any ideas?

**Comment by RandomByte** [comment]
Hey @lenient,

By default, the UI5 Tooling server only listens to connections from localhost. Since you are connecting to the server from outside the docker container, you need to pass the `--accept-remote-connections` to the `ui5 serve` command as documented [here](https://sap.github.io/ui5-tooling/pages/CLI/#serve).

Try the following:
```sh
docker run -p 8080:8080 -v $(pwd):/var/www -w "/var/www" node npm start -- --accept-remote-connections
```
