### ISSUE TITLE
ws: command not found

### ISSUE THREAD

**Issue by nbmedikonda** [SAP/openui5-sample-app#97]
Getting the below error when tried to run serve-dist

> ws --compress -d dist

sh: ws: command not found

**Comment by codeworrior** [comment]
As explained in the [README](https://github.com/SAP/openui5-sample-app#option-2-self-contained-build), the `serve-dist` script is just an example how the build results can be served. The script expects the NPM module [local-web-server](https://www.npmjs.com/package/local-web-server) to be installed (which then provides the `ws` command), but you can use any web server that you want. 

As the script only serves as a sample, its dependency is not modelled. The expectation is that developers usually have already installed a server (command) of their choice. Maybe the README could state this more clearly.

**Comment by matz3** [comment]
@codeworrior to me the README seems to be correct.

The [local-web-server is a devDependency](https://github.com/SAP/openui5-sample-app/blob/7b8db02e8eefa6ba7df80f8b746fd178fb55a25d/package.json#L25), so the reason could be a missing `npm install` (as explained in `Getting Started - 2. Install all dependencies`.

**Comment by RandomByte** [comment]
Note that executables installed via package dependencies are usually not available for direct use in your shell. Unless they are installed globally (`-g`).

So while executing `ws --compress -d dist` fails with a "command not found" error, `npm run serve-dist` works because npm also searches the `node_modules` directory for an executable named `ws`. Therefore we only explain the latter in the README.
